---
title: "Case Study: Superconductivity Critical Temperature Prediction"
author: "Megan Riley, Jaclyn Coate, Reagan Meagher"
output: pdf_document
---

## Introduction

Hello There

```{r}
library(tidyverse)
library(ggplot2)
library(GGally)


```

```{r}
train_file = "https://raw.githubusercontent.com/JaclynCoate/7333_Quantifying_The_World/main/Unit4_CaseStudy2/data/train.csv"
unique_m_file = "https://raw.githubusercontent.com/JaclynCoate/7333_Quantifying_The_World/main/Unit4_CaseStudy2/data/unique_m.csv"

train_main = read_csv(train_file)
train_chem = read_csv(unique_m_file)


```


```{r}
#ggpairs(train_main)
library(reshape2)
melted_cormat <- melt(train_main)
library(ggplot2)
ggplot(data = melted_cormat, aes(x=variable, y=variable, fill=value)) + 
  geom_tile()


```



```{r}
ggplot(data = train_main, aes(x = critical_temp)) + geom_histogram() + labs(y = "Frequency of Temp", x = "Critical Temp in Kelvin")


```



Multi Colinearity 

Major groupings of variables 

```{r}
library(corrplot)
library(RColorBrewer)
M <-cor(train_main)

#Without labels, our last column is critical temperature. 
corrplot(M, type="upper", order="original",col=brewer.pal(n=8, name="RdYlBu"), tl.pos = "n")

```

In the chemical data, there is much less multi colinearity.  

```{r}
library(corrplot)
library(RColorBrewer)
M_1 <-cor(train_chem[,-88])
M_1[is.na(M_1)] <- 0
corrplot(M_1, type="upper", order="original",col=brewer.pal(n=8, name="RdYlBu"), tl.pos = "n")
#knowing our last column is critical temperature. 

```

```{r}
#Correlation with Critical Temperature
corr_temp = data.frame(vars = names(train_main[,-82]),
                       corr = cor(train_main[,-82],train_main$critical_temp))
corr_chem_temp = data.frame(vars = names(train_chem[,-c(87,88)]) ,
                            corr = cor(train_chem[,-c(87,88)],train_main$critical_temp))
tmp = corr_chem_temp %>% filter(corr > abs(.3))
#Top four chemicals correlated with critical temperature.O, Ca, Cu, Ba 
print(tmp)
```


```{r}
#Correlation with Critical Temperature

corr_temp %>% filter(corr > .6 | corr < -.6) %>% ggplot(aes(x = vars, y = corr)) + geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + 
  labs(y = "Correlation with Critical Temperature",x = "Variables") + ggtitle("Variables Corrlated with Critical Temp Over .6")
  

```


```{r}
total_train = cbind(train_main, "O" = train_chem$O, "Ca" = train_chem$Ca, "Cu" = train_chem$Cu, "Ba"= train_chem$Ba)
train_idx = sample(seq(1,dim(total_train)[1]),round(.8*dim(total_train)[1]))
temp_train = total_train[train_idx,]
temp_test = total_train[-train_idx,]

```


```{r}


lm = lm(critical_temp ~ O + Ca + Cu + Ba + wtd_std_ThermalConductivity,data =temp_train)

summary(lm)

predict = predict(lm, temp_test)

```

```{r}
library(ModelMetrics) # rmse function

rmse = rmse(temp_test$critical_temp, predict)
print(rmse2)

```