---
title: "QTW Case Study Unit 2"
output: pdf_document
---

```{r }
library(tidyverse)
library(stringr)
library(magrittr)
library(caret)

```
```{r}
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      # record the current time before each chunk
      now <<- Sys.time()
    } else {
      # calculate the time difference after a chunk
      res <- difftime(Sys.time(), now)
      # return a character string to show the time
      paste("Time for this code chunk to run:", res)
    }
  }
}))

```


## Introduction

```{r}

#Loading data locally, something is buggy with the github links
offline_txt = readLines("/Users/zmartygirl/Documents/MSDS_SMU/QTW_7333/cs2_data/offline.final.trace.txt")
online_txt = readLines("/Users/zmartygirl/Documents/MSDS_SMU/QTW_7333/cs2_data/online.final.trace.txt")
#offline_2 = readLines("")

```

```{r}
#Functions from Provided Code
processLine = function(x)
{
tokens = strsplit(x, "[;=,]")[[1]]
if (length(tokens) == 10)
    return(NULL)
tmp = matrix(tokens[ - (1:10) ], , 4, byrow = TRUE)  #build a 4 column matrix mac,signal,scan,type
cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow(tmp), 6, #builds a 6 column matrix t,scanMac,x,y,z,angle
byrow = TRUE), tmp) #binds them together
}


roundOrientation = function(angles) {
  refs = seq(0, by = 45, length  = 9)
  q = sapply(angles, function(o) which.min(abs(o - refs)))
  c(refs[1:8], 0)[q]
}


```

Loading offline data

```{r}
off_lines = offline_txt[ substr(offline_txt, 1, 1) != "#" ]
offline = lapply(off_lines,processLine)
offline = as.data.frame(do.call("rbind", offline),stringsAsFactors = FALSE)
names(offline) = c("time", "scanMac", "posX", "posY", "posZ",
"orientation", "mac", "signal", "channel", "type")

offline$posXY = paste(offline$posX, offline$posY, sep = "-")
offline$orientation = as.integer(offline$orientation)
offline$angle = roundOrientation(offline$orientation)

```

Loading online data
```{r}
on_lines = online_txt[ substr(online_txt, 1, 1) != "#" ]
online = lapply(on_lines,processLine)
online = as.data.frame(do.call("rbind", online),stringsAsFactors = FALSE)
names(online) = c("time", "scanMac", "posX", "posY", "posZ",
"orientation", "mac", "signal", "channel", "type")

online$posXY = paste(online$posX, online$posY, sep = "-")
online$orientation = as.integer(online$orientation)

online$angle = roundOrientation(online$orientation)

```


```{r}
#Turning offline dataframe into pivot table
subMacs = names(sort(table(offline$mac), decreasing = TRUE))[1:7]
subMacs
offline1 = offline[ offline$mac %in% subMacs, ]

offline1$signal %<>% as.integer
offline_pivot<-select(offline1, -c(channel,scanMac)) %>% pivot_wider(names_from = mac,values_from = signal, values_fn = list(signal=mean))


offline_pivot$nas<-rowSums(is.na(offline_pivot))
offline_pivot = offline_pivot[offline_pivot$nas==0,]

head(offline_pivot)
```

```{r}
#Turning online dataframe into pivot table
subMacs = names(sort(table(online$mac), decreasing = TRUE))[1:7]
subMacs
online1 = online[ online$mac %in% subMacs, ]

online1$signal %<>% as.integer
online_pivot<-select(online1, -c(channel,scanMac)) %>% pivot_wider(names_from = mac,values_from = signal, values_fn = list(signal=mean))

online_pivot$nas<-rowSums(is.na(online_pivot))
online_pivot = online_pivot[online_pivot$nas==0,]

head(online_pivot)
```




```{r }
offline_subset <- select(offline_pivot, c("posX", "posY", 'posXY', "angle",
                                    "00:14:bf:b1:97:8a", "00:14:bf:b1:97:90", "00:0f:a3:39:e1:c0",
                                    "00:14:bf:b1:97:8d", "00:14:bf:b1:97:81", "00:14:bf:3b:c7:c6",
                                    "00:0f:a3:39:dd:cd"))
#Various Offline subsets

#With all available mac addresses
seven_mac_offline = offline_subset


#With the original mac address removed as in the book
original_six_mac_offline = offline_subset %>% select(-"00:0f:a3:39:dd:cd")

#With the other mac address removed
alternate_six_mac_offline = offline_subset %>% select(-"00:0f:a3:39:e1:c0")

print(options)

```

```{r}
Final_results = data.frame("Model_Type" = c("Original Six Mac Addresses", "Alternate Six Mac Addresses", "All Seven Mac Addresses", "Weighted KNN Model"), "K" = rep(0,4), "Accuracy"= rep(0,4), "Time" = rep(0,4), "RMSE" = rep(0,4))

```

 
Original Six Mac Address Analysis
```{r,time_it = TRUE}
set.seed(1234)
train.control <- trainControl(method = 'cv', number = 10)
knn.grid <- expand.grid(k = seq(2,11))

knnFit <- train(posXY ~ ., data = original_six_mac_offline %>% select(-c("posX","posY")), method = "knn", trControl = train.control, tuneGrid = knn.grid)

```

Results From First KNN Model 

```{r}
best_k = 3
Final_results[1,2] = best_k
Final_results[1,3] = knnFit$results$Accuracy[best_k] #need to report this accurayc 
#Full_Accuracy = knnFit$results #in appendix for reference
Final_results[1,4] = knnFit$times$everything[3]

```


```{r}
#original six addresses predict
knnPredict <- predict(knnFit,newdata = online_pivot %>% select(-c("posX","posY","posXY","00:0f:a3:39:dd:cd")))
temp_res = data.frame(predictions = knnPredict, TrueX = online_pivot$posX, TrueY = online_pivot$posY)

#using predictions, split into X and Y
split_x = list()
split_y = list()
for(item in seq(1:dim(temp_res)[[1]])){
  tmp = unlist(strsplit(as.character(temp_res[item,1]), "[-]"))
  split_x[item] = tmp[1]
  split_y[item] = tmp[2]
}

orig_mac_residuals = data.frame(predictions = knnPredict, PredX = as.numeric(unlist(split_x)), PredY = as.numeric(unlist(split_y)),  TrueX = as.numeric(online_pivot$posX), TrueY = as.numeric(online_pivot$posY))


diff1 =  as.numeric(orig_mac_residuals$TrueX) - as.numeric(orig_mac_residuals$PredX)
diff2 = as.numeric(orig_mac_residuals$TrueY) - as.numeric(orig_mac_residuals$PredY)
diffxy = abs(diff1) + abs(diff2)
orig_mac_residuals$diffXY = diffxy


RMSE = sqrt(sum(orig_mac_residuals$diffXY^2) / dim(orig_mac_residuals)[1])

Final_results[1,5] = RMSE
print(RMSE)

```

Alternate Mac Address Analysis 

```{r,time_it = TRUE}
set.seed(1234)
train.control <- trainControl(method = 'cv', number = 10)
knn.grid <- expand.grid(k = seq(2,11))

knnFit1 <- train(posXY ~ ., data = alternate_six_mac_offline %>% select(-c("posX","posY")), method = "knn", trControl = train.control, tuneGrid = knn.grid)

```

```{r}
best_k = 5
Final_results[2,2] = best_k
Final_results[2,3] = knnFit1$results$Accuracy[best_k] #need to report this accurayc 
#Full_Accuracy = knnFit1$results #in appendix for reference
Final_results[2,4] = knnFit1$times$everything[3]

```


```{r}
#Alternate six addresses predict
knnPredict <- predict(knnFit1,newdata = online_pivot %>% select(-c("posX","posY","posXY","00:0f:a3:39:e1:c0")))
temp_res = data.frame(predictions = knnPredict, TrueX = online_pivot$posX, TrueY = online_pivot$posY)

#using predictions, split into X and Y
split_x = list()
split_y = list()
for(item in seq(1:dim(temp_res)[[1]])){
  tmp = unlist(strsplit(as.character(temp_res[item,1]), "[-]"))
  split_x[item] = tmp[1]
  split_y[item] = tmp[2]
}

orig_mac_residuals = data.frame(predictions = knnPredict, PredX = as.numeric(unlist(split_x)), PredY = as.numeric(unlist(split_y)),  TrueX = as.numeric(online_pivot$posX), TrueY = as.numeric(online_pivot$posY))


diff1 =  as.numeric(orig_mac_residuals$TrueX) - as.numeric(orig_mac_residuals$PredX)
diff2 = as.numeric(orig_mac_residuals$TrueY) - as.numeric(orig_mac_residuals$PredY)
diffxy = abs(diff1) + abs(diff2)
orig_mac_residuals$diffXY = diffxy


RMSE = sqrt(sum(orig_mac_residuals$diffXY^2) / dim(orig_mac_residuals)[1])

Final_results[2,5] = RMSE
print(RMSE)

```

All Seven MAC Addresses

```{r,time_it = TRUE}
set.seed(1234)
train.control <- trainControl(method = 'cv', number = 10)
knn.grid <- expand.grid(k = seq(2,11))

knnFit2 <- train(posXY ~ ., data = seven_mac_offline %>% select(-c("posX","posY")), method = "knn", trControl = train.control, tuneGrid = knn.grid)

```

```{r}
best_k = 3
Final_results[3,2] = best_k
Final_results[3,3] = knnFit2$results$Accuracy[best_k] #need to report this accurayc 
#Full_Accuracy = knnFit$results #in appendix for reference
Final_results[3,4] = knnFit2$times$everything[3]

```


```{r}
#SEven addresses predict
knnPredict <- predict(knnFit2,newdata = online_pivot %>% select(-c("posX","posY","posXY")))
temp_res = data.frame(predictions = knnPredict, TrueX = online_pivot$posX, TrueY = online_pivot$posY)

#using predictions, split into X and Y
split_x = list()
split_y = list()
for(item in seq(1:dim(temp_res)[[1]])){
  tmp = unlist(strsplit(as.character(temp_res[item,1]), "[-]"))
  split_x[item] = tmp[1]
  split_y[item] = tmp[2]
}

orig_mac_residuals = data.frame(predictions = knnPredict, PredX = as.numeric(unlist(split_x)), PredY = as.numeric(unlist(split_y)),  TrueX = as.numeric(online_pivot$posX), TrueY = as.numeric(online_pivot$posY))


diff1 =  as.numeric(orig_mac_residuals$TrueX) - as.numeric(orig_mac_residuals$PredX)
diff2 = as.numeric(orig_mac_residuals$TrueY) - as.numeric(orig_mac_residuals$PredY)
diffxy = abs(diff1) + abs(diff2)
orig_mac_residuals$diffXY = diffxy


RMSE = sqrt(sum(orig_mac_residuals$diffXY^2) / dim(orig_mac_residuals)[1])

Final_results[3,5] = RMSE
print(RMSE)

```

